/**
 * Curated problem catalog - identity data only.
 *
 * This file contains ONLY: id, title, url, difficulty, topics.
 * NO intuitions, notes, answers, hints, or solutions per charter §6.2.
 * NO user progress data per charter §6.1.
 *
 * Generated from founder's curated Notion export via scripts/import-catalog.ts.
 * To regenerate: run the importer script and replace this file.
 */

import type { Problem } from './index.js';

/**
 * The curated problem catalog.
 * 175 problems across 15 topics.
 */
export const CATALOG: readonly Problem[] = [
  {
    id: 'lc-3',
    title: 'Longest Substring Without Repeating Characters',
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    difficulty: 'medium',
    topics: ['sliding-window'],
  },
  {
    id: 'lc-4',
    title: 'Median of Two Sorted Arrays',
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    difficulty: 'hard',
    topics: ['miscellaneous'],
  },
  {
    id: 'lc-11',
    title: 'Container With Most Water',
    url: 'https://leetcode.com/problems/container-with-most-water/',
    difficulty: 'medium',
    topics: ['sliding-window'],
  },
  {
    id: 'lc-17',
    title: 'Letter Combinations of a Phone Number',
    url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-19',
    title: 'Remove Nth Node From End of List',
    url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    difficulty: 'medium',
    topics: ['linked-list'],
  },
  {
    id: 'lc-21',
    title: 'Merge Two Sorted Lists',
    url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-23',
    title: 'Merge k Sorted Lists',
    url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    difficulty: 'hard',
    topics: ['heap'],
  },
  {
    id: 'lc-25',
    title: 'Reverse Nodes in k-Group',
    url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    difficulty: 'hard',
    topics: ['linked-list'],
  },
  {
    id: 'lc-26',
    title: 'Remove Duplicates from Sorted Array',
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
    difficulty: 'easy',
    topics: ['binary-search'],
  },
  {
    id: 'lc-31',
    title: 'Next Permutation',
    url: 'https://leetcode.com/problems/next-permutation/',
    difficulty: 'medium',
    topics: ['miscellaneous'],
  },
  {
    id: 'lc-32',
    title: 'Longest Valid Parentheses',
    url: 'https://leetcode.com/problems/longest-valid-parentheses/',
    difficulty: 'hard',
    topics: ['stack'],
  },
  {
    id: 'lc-33',
    title: 'Search in Rotated Sorted Array',
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-34',
    title: 'Find First and Last Position of Element in Sorted Array',
    url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-36',
    title: 'Valid Sudoku',
    url: 'https://leetcode.com/problems/valid-sudoku/',
    difficulty: 'easy',
    topics: ['hashing'],
  },
  {
    id: 'lc-39',
    title: 'Combination Sum',
    url: 'https://leetcode.com/problems/combination-sum/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-42',
    title: 'Trapping Rain Water',
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    difficulty: 'hard',
    topics: ['two-pointers'],
  },
  {
    id: 'lc-44',
    title: 'Wildcard Matching',
    url: 'https://leetcode.com/problems/wildcard-matching/',
    difficulty: 'hard',
    topics: ['recursion'],
  },
  {
    id: 'lc-46',
    title: 'Permutations',
    url: 'https://leetcode.com/problems/permutations/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-47',
    title: 'Permutations II',
    url: 'https://leetcode.com/problems/permutations-ii/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-53',
    title: 'Maximum Subarray',
    url: 'https://leetcode.com/problems/maximum-subarray/',
    difficulty: 'easy',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-54',
    title: 'Spiral Matrix',
    url: 'https://leetcode.com/problems/spiral-matrix/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-62',
    title: 'Unique Paths',
    url: 'https://leetcode.com/problems/unique-paths/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-70',
    title: 'Climbing Stairs',
    url: 'https://leetcode.com/problems/climbing-stairs/',
    difficulty: 'easy',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-72',
    title: 'Edit Distance',
    url: 'https://leetcode.com/problems/edit-distance/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-74',
    title: 'Search a 2D Matrix',
    url: 'https://leetcode.com/problems/search-a-2d-matrix/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-75',
    title: 'Sort Colors',
    url: 'https://leetcode.com/problems/sort-colors/',
    difficulty: 'medium',
    topics: ['sorting'],
  },
  {
    id: 'lc-77',
    title: 'Combinations',
    url: 'https://leetcode.com/problems/combinations/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-78',
    title: 'Subsets',
    url: 'https://leetcode.com/problems/subsets/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-79',
    title: 'Word Search',
    url: 'https://leetcode.com/problems/word-search/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-84',
    title: 'Largest Rectangle in Histogram',
    url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    difficulty: 'hard',
    topics: ['stack'],
  },
  {
    id: 'lc-91',
    title: 'Decode Ways',
    url: 'https://leetcode.com/problems/decode-ways/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-92',
    title: 'Reverse Linked List II',
    url: 'https://leetcode.com/problems/reverse-linked-list-ii/',
    difficulty: 'medium',
    topics: ['linked-list'],
  },
  {
    id: 'lc-100',
    title: 'Same Tree',
    url: 'https://leetcode.com/problems/same-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-102',
    title: 'Binary Tree Level Order Traversal',
    url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-104',
    title: 'Maximum Depth of Binary Tree',
    url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-105',
    title: 'Construct Binary Tree from Preorder and Inorder Traversal',
    url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-106',
    title: 'Construct Binary Tree from Inorder and Postorder Traversal',
    url: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-110',
    title: 'Balanced Binary Tree',
    url: 'https://leetcode.com/problems/balanced-binary-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-112',
    title: 'Path Sum',
    url: 'https://leetcode.com/problems/path-sum/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-113',
    title: 'Path Sum II',
    url: 'https://leetcode.com/problems/path-sum-ii/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-118',
    title: "Pascal's Triangle",
    url: 'https://leetcode.com/problems/pascals-triangle/',
    difficulty: 'easy',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-121',
    title: 'Best Time to Buy and Sell Stock',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    difficulty: 'easy',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-122',
    title: 'Best Time to Buy and Sell Stock II',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-123',
    title: 'Best Time to Buy and Sell Stock III',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-127',
    title: 'Word Ladder',
    url: 'https://leetcode.com/problems/word-ladder/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-128',
    title: 'Longest Consecutive Sequence',
    url: 'https://leetcode.com/problems/longest-consecutive-sequence/',
    difficulty: 'medium',
    topics: ['hashing'],
  },
  {
    id: 'lc-132',
    title: 'Palindrome Partitioning II',
    url: 'https://leetcode.com/problems/palindrome-partitioning-ii/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-135',
    title: 'Candy',
    url: 'https://leetcode.com/problems/candy/',
    difficulty: 'hard',
    topics: ['greedy'],
  },
  {
    id: 'lc-141',
    title: 'Linked List Cycle',
    url: 'https://leetcode.com/problems/linked-list-cycle/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-142',
    title: 'Linked List Cycle II',
    url: 'https://leetcode.com/problems/linked-list-cycle-ii/',
    difficulty: 'medium',
    topics: ['linked-list'],
  },
  {
    id: 'lc-148',
    title: 'Sort List',
    url: 'https://leetcode.com/problems/sort-list/',
    difficulty: 'medium',
    topics: ['linked-list'],
  },
  {
    id: 'lc-149',
    title: 'Max Points on a Line',
    url: 'https://leetcode.com/problems/max-points-on-a-line/',
    difficulty: 'hard',
    topics: ['hashing'],
  },
  {
    id: 'lc-150',
    title: 'Evaluate Reverse Polish Notation',
    url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-155',
    title: 'Min Stack',
    url: 'https://leetcode.com/problems/min-stack/',
    difficulty: 'easy',
    topics: ['stack'],
  },
  {
    id: 'lc-162',
    title: 'Find Peak Element',
    url: 'https://leetcode.com/problems/find-peak-element/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-167',
    title: 'Two Sum II - Input Array Is Sorted',
    url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
    difficulty: 'medium',
    topics: ['two-pointers'],
  },
  {
    id: 'lc-172',
    title: 'Factorial Trailing Zeroes',
    url: 'https://leetcode.com/problems/factorial-trailing-zeroes/',
    difficulty: 'easy',
    topics: ['binary-search'],
  },
  {
    id: 'lc-188',
    title: 'Best Time to Buy and Sell Stock IV',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-199',
    title: 'Binary Tree Right Side View',
    url: 'https://leetcode.com/problems/binary-tree-right-side-view/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-203',
    title: 'Remove Linked List Elements',
    url: 'https://leetcode.com/problems/remove-linked-list-elements/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-206',
    title: 'Reverse Linked List',
    url: 'https://leetcode.com/problems/reverse-linked-list/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-207',
    title: 'Course Schedule',
    url: 'https://leetcode.com/problems/course-schedule/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-208',
    title: 'Implement Trie (Prefix Tree)',
    url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-209',
    title: 'Minimum Size Subarray Sum',
    url: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
    difficulty: 'medium',
    topics: ['arrays-2d', 'sliding-window'],
  },
  {
    id: 'lc-210',
    title: 'Course Schedule II',
    url: 'https://leetcode.com/problems/course-schedule-ii/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-211',
    title: 'Design Add and Search Words Data Structure',
    url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-212',
    title: 'Word Search II',
    url: 'https://leetcode.com/problems/word-search-ii/',
    difficulty: 'hard',
    topics: ['trees'],
  },
  {
    id: 'lc-215',
    title: 'Kth Largest Element in an Array',
    url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
    difficulty: 'medium',
    topics: ['sorting'],
  },
  {
    id: 'lc-219',
    title: 'Contains Duplicate II',
    url: 'https://leetcode.com/problems/contains-duplicate-ii/',
    difficulty: 'easy',
    topics: ['sliding-window'],
  },
  {
    id: 'lc-224',
    title: 'Basic Calculator',
    url: 'https://leetcode.com/problems/basic-calculator/',
    difficulty: 'hard',
    topics: ['stack'],
  },
  {
    id: 'lc-225',
    title: 'Implement Stack using Queues',
    url: 'https://leetcode.com/problems/implement-stack-using-queues/',
    difficulty: 'easy',
    topics: ['stack'],
  },
  {
    id: 'lc-226',
    title: 'Invert Binary Tree',
    url: 'https://leetcode.com/problems/invert-binary-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-232',
    title: 'Implement Queue using Stacks',
    url: 'https://leetcode.com/problems/implement-queue-using-stacks/',
    difficulty: 'easy',
    topics: ['stack'],
  },
  {
    id: 'lc-234',
    title: 'Palindrome Linked List',
    url: 'https://leetcode.com/problems/palindrome-linked-list/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-235',
    title: 'Lowest Common Ancestor of a Binary Search Tree',
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-237',
    title: 'Delete Node in a Linked List',
    url: 'https://leetcode.com/problems/delete-node-in-a-linked-list/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-239',
    title: 'Sliding Window Maximum',
    url: 'https://leetcode.com/problems/sliding-window-maximum/',
    difficulty: 'hard',
    topics: ['stack'],
  },
  {
    id: 'lc-242',
    title: 'Valid Anagram',
    url: 'https://leetcode.com/problems/valid-anagram/',
    difficulty: 'easy',
    topics: ['hashing'],
  },
  {
    id: 'lc-253',
    title: 'Meeting Rooms II',
    url: 'https://leetcode.com/problems/meeting-rooms-ii/',
    difficulty: 'medium',
    topics: ['heap'],
  },
  {
    id: 'lc-264',
    title: 'Ugly Number II',
    url: 'https://leetcode.com/problems/ugly-number-ii/',
    difficulty: 'medium',
    topics: ['hashing'],
  },
  {
    id: 'lc-269',
    title: 'Alien Dictionary',
    url: 'https://leetcode.com/problems/alien-dictionary/',
    difficulty: 'hard',
    topics: ['graphs'],
  },
  {
    id: 'lc-272',
    title: 'Closest Binary Search Tree Value II',
    url: 'https://leetcode.com/problems/closest-binary-search-tree-value-ii/',
    difficulty: 'hard',
    topics: ['trees'],
  },
  {
    id: 'lc-295',
    title: 'Find Median from Data Stream',
    url: 'https://leetcode.com/problems/find-median-from-data-stream/',
    difficulty: 'hard',
    topics: ['heap'],
  },
  {
    id: 'lc-300',
    title: 'Longest Increasing Subsequence',
    url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-304',
    title: 'Range Sum Query 2D - Immutable',
    url: 'https://leetcode.com/problems/range-sum-query-2d-immutable/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-307',
    title: 'Range Sum Query - Mutable',
    url: 'https://leetcode.com/problems/range-sum-query-mutable/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-309',
    title: 'Best Time to Buy and Sell Stock with Cooldown',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-312',
    title: 'Burst Balloons',
    url: 'https://leetcode.com/problems/burst-balloons/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-319',
    title: 'Bulb Switcher',
    url: 'https://leetcode.com/problems/bulb-switcher/',
    difficulty: 'medium',
    topics: ['greedy'],
  },
  {
    id: 'lc-322',
    title: 'Coin Change',
    url: 'https://leetcode.com/problems/coin-change/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-336',
    title: 'Palindrome Pairs',
    url: 'https://leetcode.com/problems/palindrome-pairs/',
    difficulty: 'hard',
    topics: ['hashing'],
  },
  {
    id: 'lc-347',
    title: 'Top K Frequent Elements',
    url: 'https://leetcode.com/problems/top-k-frequent-elements/',
    difficulty: 'medium',
    topics: ['heap'],
  },
  {
    id: 'lc-354',
    title: 'Russian Doll Envelopes',
    url: 'https://leetcode.com/problems/russian-doll-envelopes/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-368',
    title: 'Largest Divisible Subset',
    url: 'https://leetcode.com/problems/largest-divisible-subset/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-373',
    title: 'Find K Pairs with Smallest Sums',
    url: 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/',
    difficulty: 'medium',
    topics: ['heap'],
  },
  {
    id: 'lc-402',
    title: 'Remove K Digits',
    url: 'https://leetcode.com/problems/remove-k-digits/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-403',
    title: 'Frog Jump',
    url: 'https://leetcode.com/problems/frog-jump/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-404',
    title: 'Sum of Left Leaves',
    url: 'https://leetcode.com/problems/sum-of-left-leaves/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-406',
    title: 'Queue Reconstruction by Height',
    url: 'https://leetcode.com/problems/queue-reconstruction-by-height/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-416',
    title: 'Partition Equal Subset Sum',
    url: 'https://leetcode.com/problems/partition-equal-subset-sum/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-424',
    title: 'Longest Repeating Character Replacement',
    url: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    difficulty: 'medium',
    topics: ['sliding-window'],
  },
  {
    id: 'lc-435',
    title: 'Non-overlapping Intervals',
    url: 'https://leetcode.com/problems/non-overlapping-intervals/',
    difficulty: 'medium',
    topics: ['greedy'],
  },
  {
    id: 'lc-437',
    title: 'Path Sum III',
    url: 'https://leetcode.com/problems/path-sum-iii/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-474',
    title: 'Ones and Zeroes',
    url: 'https://leetcode.com/problems/ones-and-zeroes/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-493',
    title: 'Reverse Pairs',
    url: 'https://leetcode.com/problems/reverse-pairs/',
    difficulty: 'hard',
    topics: ['miscellaneous'],
  },
  {
    id: 'lc-503',
    title: 'Next Greater Element II',
    url: 'https://leetcode.com/problems/next-greater-element-ii/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-516',
    title: 'Longest Palindromic Subsequence',
    url: 'https://leetcode.com/problems/longest-palindromic-subsequence/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-518',
    title: 'Coin Change II',
    url: 'https://leetcode.com/problems/coin-change-ii/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-525',
    title: 'Contiguous Array',
    url: 'https://leetcode.com/problems/contiguous-array/',
    difficulty: 'medium',
    topics: ['hashing'],
  },
  {
    id: 'lc-532',
    title: 'K-diff Pairs in an Array',
    url: 'https://leetcode.com/problems/k-diff-pairs-in-an-array/',
    difficulty: 'medium',
    topics: ['two-pointers'],
  },
  {
    id: 'lc-540',
    title: 'Single Element in a Sorted Array',
    url: 'https://leetcode.com/problems/single-element-in-a-sorted-array/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-542',
    title: '01 Matrix',
    url: 'https://leetcode.com/problems/01-matrix/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-547',
    title: 'Number of Provinces',
    url: 'https://leetcode.com/problems/number-of-provinces/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-560',
    title: 'Subarray Sum Equals K',
    url: 'https://leetcode.com/problems/subarray-sum-equals-k/',
    difficulty: 'medium',
    topics: ['hashing'],
  },
  {
    id: 'lc-628',
    title: 'Maximum Product of Three Numbers',
    url: 'https://leetcode.com/problems/maximum-product-of-three-numbers/',
    difficulty: 'easy',
    topics: ['greedy'],
  },
  {
    id: 'lc-658',
    title: 'Find K Closest Elements',
    url: 'https://leetcode.com/problems/find-k-closest-elements/',
    difficulty: 'medium',
    topics: ['two-pointers'],
  },
  {
    id: 'lc-669',
    title: 'Trim a Binary Search Tree',
    url: 'https://leetcode.com/problems/trim-a-binary-search-tree/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-670',
    title: 'Maximum Swap',
    url: 'https://leetcode.com/problems/maximum-swap/',
    difficulty: 'medium',
    topics: ['greedy'],
  },
  {
    id: 'lc-682',
    title: 'Baseball Game',
    url: 'https://leetcode.com/problems/baseball-game/',
    difficulty: 'easy',
    topics: ['stack'],
  },
  {
    id: 'lc-684',
    title: 'Redundant Connection',
    url: 'https://leetcode.com/problems/redundant-connection/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-700',
    title: 'Search in a Binary Search Tree',
    url: 'https://leetcode.com/problems/search-in-a-binary-search-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-714',
    title: 'Best Time to Buy and Sell Stock with Transaction Fee',
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-721',
    title: 'Accounts Merge',
    url: 'https://leetcode.com/problems/accounts-merge/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-728',
    title: 'Self Dividing Numbers',
    url: 'https://leetcode.com/problems/self-dividing-numbers/',
    difficulty: 'easy',
    topics: ['miscellaneous'],
  },
  {
    id: 'lc-739',
    title: 'Daily Temperatures',
    url: 'https://leetcode.com/problems/daily-temperatures/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-743',
    title: 'Network Delay Time',
    url: 'https://leetcode.com/problems/network-delay-time/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-769',
    title: 'Max Chunks To Make Sorted',
    url: 'https://leetcode.com/problems/max-chunks-to-make-sorted/',
    difficulty: 'medium',
    topics: ['sorting'],
  },
  {
    id: 'lc-787',
    title: 'Cheapest Flights Within K Stops',
    url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-793',
    title: 'Preimage Size of Factorial Zeroes Function',
    url: 'https://leetcode.com/problems/preimage-size-of-factorial-zeroes-function/',
    difficulty: 'hard',
    topics: ['binary-search'],
  },
  {
    id: 'lc-802',
    title: 'Find Eventual Safe States',
    url: 'https://leetcode.com/problems/find-eventual-safe-states/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-814',
    title: 'Binary Tree Pruning',
    url: 'https://leetcode.com/problems/binary-tree-pruning/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-844',
    title: 'Backspace String Compare',
    url: 'https://leetcode.com/problems/backspace-string-compare/',
    difficulty: 'easy',
    topics: ['stack'],
  },
  {
    id: 'lc-847',
    title: 'Shortest Path Visiting All Nodes',
    url: 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-867',
    title: 'Transpose Matrix',
    url: 'https://leetcode.com/problems/transpose-matrix/',
    difficulty: 'easy',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-875',
    title: 'Koko Eating Bananas',
    url: 'https://leetcode.com/problems/koko-eating-bananas/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-876',
    title: 'Middle of the Linked List',
    url: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-907',
    title: 'Sum of Subarray Minimums',
    url: 'https://leetcode.com/problems/sum-of-subarray-minimums/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-918',
    title: 'Maximum Sum Circular Subarray',
    url: 'https://leetcode.com/problems/maximum-sum-circular-subarray/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-973',
    title: 'K Closest Points to Origin',
    url: 'https://leetcode.com/problems/k-closest-points-to-origin/',
    difficulty: 'medium',
    topics: ['heap'],
  },
  {
    id: 'lc-978',
    title: 'Longest Turbulent Subarray',
    url: 'https://leetcode.com/problems/longest-turbulent-subarray/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-994',
    title: 'Rotting Oranges',
    url: 'https://leetcode.com/problems/rotting-oranges/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1005',
    title: 'Maximize Sum Of Array After K Negations',
    url: 'https://leetcode.com/problems/maximize-sum-of-array-after-k-negations/',
    difficulty: 'easy',
    topics: ['greedy'],
  },
  {
    id: 'lc-1011',
    title: 'Capacity To Ship Packages Within D Days',
    url: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-1020',
    title: 'Number of Enclaves',
    url: 'https://leetcode.com/problems/number-of-enclaves/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1048',
    title: 'Longest String Chain',
    url: 'https://leetcode.com/problems/longest-string-chain/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1049',
    title: 'Last Stone Weight II',
    url: 'https://leetcode.com/problems/last-stone-weight-ii/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1091',
    title: 'Shortest Path in Binary Matrix',
    url: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1106',
    title: 'Parsing A Boolean Expression',
    url: 'https://leetcode.com/problems/parsing-a-boolean-expression/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1130',
    title: 'Minimum Cost Tree From Leaf Values',
    url: 'https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/',
    difficulty: 'medium',
    topics: ['trees'],
  },
  {
    id: 'lc-1135',
    title: 'Connecting Cities With Minimum Cost',
    url: 'https://leetcode.com/problems/connecting-cities-with-minimum-cost/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1143',
    title: 'Longest Common Subsequence',
    url: 'https://leetcode.com/problems/longest-common-subsequence/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1200',
    title: 'Minimum Absolute Difference',
    url: 'https://leetcode.com/problems/minimum-absolute-difference/',
    difficulty: 'easy',
    topics: ['sorting'],
  },
  {
    id: 'lc-1231',
    title: 'Divide Chocolate',
    url: 'https://leetcode.com/problems/divide-chocolate/',
    difficulty: 'hard',
    topics: ['binary-search'],
  },
  {
    id: 'lc-1249',
    title: 'Minimum Remove to Make Valid Parentheses',
    url: 'https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/',
    difficulty: 'medium',
    topics: ['stack'],
  },
  {
    id: 'lc-1290',
    title: 'Convert Binary Number in a Linked List to Integer',
    url: 'https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/',
    difficulty: 'easy',
    topics: ['linked-list'],
  },
  {
    id: 'lc-1310',
    title: 'XOR Queries of a Subarray',
    url: 'https://leetcode.com/problems/xor-queries-of-a-subarray/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-1312',
    title: 'Minimum Insertion Steps to Make a String Palindrome',
    url: 'https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/',
    difficulty: 'hard',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1334',
    title:
      'Find the City With the Smallest Number of Neighbors at a Threshold Distance',
    url: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1343',
    title:
      'Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold',
    url: 'https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/',
    difficulty: 'medium',
    topics: ['sliding-window'],
  },
  {
    id: 'lc-1351',
    title: 'Count Negative Numbers in a Sorted Matrix',
    url: 'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/',
    difficulty: 'easy',
    topics: ['miscellaneous'],
  },
  {
    id: 'lc-1382',
    title: 'Balance a Binary Search Tree',
    url: 'https://leetcode.com/problems/balance-a-binary-search-tree/',
    difficulty: 'easy',
    topics: ['trees'],
  },
  {
    id: 'lc-1462',
    title: 'Course Schedule IV',
    url: 'https://leetcode.com/problems/course-schedule-iv/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1480',
    title: 'Running Sum of 1d Array',
    url: 'https://leetcode.com/problems/running-sum-of-1d-array/',
    difficulty: 'easy',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-1482',
    title: 'Minimum Number of Days to Make m Bouquets',
    url: 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-1489',
    title: 'Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree',
    url: 'https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/',
    difficulty: 'hard',
    topics: ['graphs'],
  },
  {
    id: 'lc-1582',
    title: 'Special Positions in a Binary Matrix',
    url: 'https://leetcode.com/problems/special-positions-in-a-binary-matrix/',
    difficulty: 'medium',
    topics: ['arrays-2d'],
  },
  {
    id: 'lc-1584',
    title: 'Min Cost to Connect All Points',
    url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-1654',
    title: 'Minimum Jumps to Reach Home',
    url: 'https://leetcode.com/problems/minimum-jumps-to-reach-home/',
    difficulty: 'medium',
    topics: ['dynamic-programming'],
  },
  {
    id: 'lc-1870',
    title: 'Minimum Speed to Arrive on Time',
    url: 'https://leetcode.com/problems/minimum-speed-to-arrive-on-time/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-1922',
    title: 'Count Good Numbers',
    url: 'https://leetcode.com/problems/count-good-numbers/',
    difficulty: 'medium',
    topics: ['recursion'],
  },
  {
    id: 'lc-1976',
    title: 'Number of Ways to Arrive at Destination',
    url: 'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/',
    difficulty: 'medium',
    topics: ['graphs'],
  },
  {
    id: 'lc-2130',
    title: 'Maximum Twin Sum of a Linked List',
    url: 'https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/',
    difficulty: 'medium',
    topics: ['linked-list'],
  },
  {
    id: 'lc-2407',
    title: 'Longest Increasing Subsequence II',
    url: 'https://leetcode.com/problems/longest-increasing-subsequence-ii/',
    difficulty: 'hard',
    topics: ['trees'],
  },
  {
    id: 'lc-2594',
    title: 'Minimum Time to Repair Cars',
    url: 'https://leetcode.com/problems/minimum-time-to-repair-cars/',
    difficulty: 'medium',
    topics: ['binary-search'],
  },
  {
    id: 'lc-3532',
    title: 'Path Existence Queries in a Graph I',
    url: 'https://leetcode.com/problems/path-existence-queries-in-a-graph-i/',
    difficulty: 'medium',
    topics: ['miscellaneous'],
  },
];
